(() => {
  const params = new URLSearchParams(location.search);
  const roomId = (params.get('roomid') || '').trim().toLowerCase();
  const name = (params.get('name') || localStorage.getItem('felt-player-name') || 'PLAYER').trim().slice(0, 16) || 'PLAYER';
  const playerId = sessionStorage.getItem('felt-player-id') || crypto.randomUUID();
  sessionStorage.setItem('felt-player-id', playerId);
  let connected = false;
  let assetsReady = false;
  let joined = false;
  const channel = window.FeltRealtime.connect(roomId, handleMessage, status => { if (status === 'SUBSCRIBED') { connected = true; startWhenReady(); } });
  const lobby = window.FeltRealtime.lobby(data => { if (data.type === 'rooms') publishRoom(); });
  const $ = id => document.getElementById(id);
  const imagePath = card => card.joker ? '../cards/j01@2x.png' : `../cards/${card.suit}${String(card.rank).padStart(2, '0')}@2x.png`;
  const handNames = ['ハイカード', 'ワンペア', 'ツーペア', 'スリーカード', 'ストレート', 'フラッシュ', 'フルハウス', 'フォーカード', 'ストレートフラッシュ'];
  let state = { room: { id: roomId }, players: [], phase: 'waiting', pot: 0, round: 0, exchangeRound: 1, turnOrder: [], currentTurn: null, hostId: null, winner: null, settings: { startingCoins: 500, betUnit: 10, turns: 1, jokerCount: 0, cpuCount: 0 }, message: '参加者を待っています' };
  let deck = [];
  let selected = new Set();
  const send = payload => channel.send({ ...payload, from: playerId });
  const toast = text => { $('toast').textContent = text; $('toast').classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => $('toast').classList.remove('show'), 2400); };
  const cardAssets = ['../cards/back@2x.png', '../cards/j01@2x.png', ...['s', 'h', 'd', 'c'].flatMap(suit => Array.from({ length: 13 }, (_, i) => `../cards/${suit}${String(i + 1).padStart(2, '0')}@2x.png`))];
  function preloadAssets() { const progress = $('loadingProgress'); const status = $('loadingStatus'); let loaded = 0; return Promise.all(cardAssets.map(path => new Promise(resolve => { const image = new Image(); image.onload = image.onerror = () => { loaded += 1; progress.style.width = `${Math.round(loaded / cardAssets.length * 100)}%`; status.textContent = `カード画像を準備中... ${loaded} / ${cardAssets.length}`; resolve(); }; image.src = path; }))).then(() => { assetsReady = true; status.textContent = 'カードの準備が完了しました'; $('offlineLoading').classList.add('ready'); startWhenReady(); }); }
  function startWhenReady() { if (connected && assetsReady && !joined) { joined = true; join(); } }
  function makeDeck() { const deck = ['s', 'h', 'd', 'c'].flatMap(suit => Array.from({ length: 13 }, (_, i) => ({ suit, rank: i + 1, id: `${suit}${i + 1}` }))); for (let i = 0; i < state.settings.jokerCount; i += 1) deck.push({ joker: true, id: `joker-${i}` }); return deck; }
  function shuffle(cards) { for (let i = cards.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [cards[i], cards[j]] = [cards[j], cards[i]]; } return cards; }
  function evaluate(hand) { const jokers = hand.filter(card => card.joker).length; const natural = hand.filter(card => !card.joker); const ranks = natural.map(card => card.rank === 1 ? 14 : card.rank).sort((a, b) => b - a); const counts = Object.values(ranks.reduce((map, rank) => ({ ...map, [rank]: (map[rank] || 0) + 1 }), {})).sort((a, b) => b - a); const flush = natural.length === 5 && new Set(natural.map(card => card.suit)).size === 1; const unique = [...new Set(ranks)]; const straight = unique.length === 5 && (unique[0] - unique[4] === 4 || unique.join(',') === '14,5,4,3,2'); const rank = jokers >= 4 ? 8 : jokers && counts[0] >= 4 ? 7 : counts[0] + jokers >= 4 ? 7 : counts[0] + jokers >= 3 && counts[1] >= 2 ? 6 : straight && flush || jokers && unique.length >= 4 ? 8 : flush ? 5 : straight ? 4 : counts[0] + jokers >= 3 ? 3 : counts[0] + jokers >= 2 && counts[1] >= 2 ? 2 : counts[0] + jokers >= 2 ? 1 : 0; return { rank, name: jokers ? `${handNames[rank]} · JOKER WILD` : handNames[rank] }; }
  function join() { if (!state.hostId) { state.hostId = playerId; state.players.push({ id: playerId, name, hand: [], handCount: 0, folded: false, ready: false }); render(); } send({ type: 'join', player: { id: playerId, name, hand: [], handCount: 0, folded: false, ready: false } }); publishRoom(); }
  function publishRoom() { lobby.send({ type: 'room', rooms: [{ id: roomId, name: roomId, players: state.players.length, maxPlayers: 6, playing: state.phase === 'draw' }] }); }
  function broadcastState() { render(); send({ type: 'state', state }); publishRoom(); }
  function host() { return state.hostId === playerId; }
  function handleMessage(data) {
    if (data.type === 'room') { if (location.pathname.endsWith('/room.html')) renderRooms(data.rooms); return; }
    if (data.type === 'rooms') { publishRoom(); return; }
    if (data.type === 'join' && (!state.hostId || host())) { if (!state.hostId) state.hostId = playerId; if (!state.players.some(player => player.id === data.player.id)) state.players.push(data.player); broadcastState(); return; }
    if (data.type === 'settings' && host() && state.phase !== 'draw') { state.settings = { ...state.settings, ...data.settings }; state.message = '設定を保存しました'; broadcastState(); return; }
    if (data.type === 'start' && host() && state.players.length >= 2) { const humans = state.players.filter(player => !player.cpu); const cpuPlayers = Array.from({ length: state.settings.cpuCount }, (_, index) => ({ id: `cpu-${index + 1}`, name: `CPU ${String(index + 1).padStart(2, '0')}`, cpu: true, hand: [], handCount: 0, folded: false, ready: false, coins: state.settings.startingCoins })); state.players = [...humans, ...cpuPlayers]; deck = shuffle(makeDeck()); state.players.forEach(player => { player.hand = deck.splice(0, 5); player.handCount = 5; player.ready = false; player.folded = false; player.coins = player.coins || state.settings.startingCoins; }); state = { ...state, phase: 'draw', exchangeRound: 1, turnOrder: state.players.map(player => player.id), currentTurn: state.players[0].id, round: state.round + 1, pot: state.players.length * state.settings.betUnit, winner: null, message: `${state.players[0].name}のターン · 交換するカードを選択` }; broadcastState(); processCpuTurn(); return; }
    if (data.type === 'draw' && host() && state.phase === 'draw') { const player = state.players.find(item => item.id === data.from); if (!player || player.ready || player.id !== state.currentTurn || player.folded) return; [...new Set(data.indexes || [])].filter(index => index >= 0 && index < 5).forEach(index => { player.hand[index] = deck.pop(); }); player.ready = true; advanceTurn(); return; }
    if (data.type === 'fold' && host() && state.phase === 'draw') { const player = state.players.find(item => item.id === data.from); if (!player || player.id !== state.currentTurn) return; player.folded = true; player.ready = true; if (state.players.filter(item => !item.folded).length <= 1) finish(); else advanceTurn(); return; }
    if (data.type === 'state') { state = data.state; render(); }
  }
  function advanceTurn() { const active = state.players.filter(player => !player.folded); const remaining = active.find(player => !player.ready); if (!remaining) { if (state.exchangeRound < state.settings.turns) { state.exchangeRound += 1; active.forEach(player => { player.ready = false; }); state.currentTurn = active[0].id; state.message = `交換ラウンド ${state.exchangeRound} / ${state.settings.turns} · ${active[0].name}のターン`; broadcastState(); processCpuTurn(); } else finish(); return; } const currentIndex = state.turnOrder.indexOf(state.currentTurn); const ordered = [...state.turnOrder.slice(currentIndex + 1), ...state.turnOrder.slice(0, currentIndex + 1)]; state.currentTurn = ordered.find(id => active.some(player => player.id === id && !player.ready)) || remaining.id; const next = state.players.find(player => player.id === state.currentTurn); state.message = `${next.name}のターン · カードを選択`; broadcastState(); processCpuTurn(); }
  function processCpuTurn() { const player = state.players.find(item => item.id === state.currentTurn); if (!player?.cpu || player.ready || state.phase !== 'draw') return; const hand = evaluate(player.hand); const indexes = hand.rank >= 4 ? [] : player.hand.map((_, index) => index).slice(0, Math.min(2, state.settings.jokerCount ? 1 : 2)); handleMessage({ type: 'draw', from: player.id, indexes }); }
  function finish() { const alive = state.players.filter(player => !player.folded); const winner = alive.reduce((best, player) => evaluate(player.hand).rank > evaluate(best.hand).rank ? player : best, alive[0]); state = { ...state, phase: 'finished', winner: winner.id, message: `${winner.name} が ${evaluate(winner.hand).name} で勝利しました` }; broadcastState(); }
  function renderPlayers() { $('playerCount').textContent = String(state.players.length).padStart(2, '0'); $('playerList').innerHTML = state.players.map(player => { const reveal = state.phase === 'finished' && player.hand.length; const cards = player.id === playerId ? '' : `<div class="opponent-hand">${player.hand.map(card => `<img class="mini-card ${reveal ? 'revealed-card' : 'hidden-card'}" src="${reveal ? imagePath(card) : '../cards/back@2x.png'}" alt="${reveal ? `${player.name}のカード` : '相手の伏せカード'}">`).join('')}</div><div class="opponent-evaluation">${reveal ? evaluate(player.hand).name : '非公開'}</div>`; return `<div class="player ${player.id === playerId ? 'active' : ''} ${player.folded ? 'folded' : ''}"><div class="player-main"><div class="avatar ${player.id === playerId ? 'you' : ''}">${player.id === playerId ? 'YOU' : player.name.slice(0, 2).toUpperCase()}</div><div><div class="player-name">${player.name}${player.id === playerId ? ' · あなた' : ''}</div><div class="player-state">${player.folded ? 'FOLDED' : player.ready ? 'READY' : player.id === state.hostId ? 'HOST' : 'IN TABLE'}</div></div><div class="player-coins">${player.coins ?? state.settings.startingCoins} coins</div></div>${cards}</div>`; }).join(''); }
  function renderHand() { const player = state.players.find(item => item.id === playerId); const hand = player?.hand || []; $('playerHand').innerHTML = hand.map((card, index) => `<div class="playing-card ${selected.has(index) ? 'selected' : ''}" data-index="${index}"><img src="${imagePath(card)}" alt="カード ${index + 1}"></div>`).join(''); $('selectionCount').textContent = `${selected.size} / 5 selected`; $('exchangeButton').disabled = state.phase !== 'draw' || player?.ready || player?.folded || state.currentTurn !== playerId; $('handEvaluation').textContent = player?.hand?.length ? evaluate(player.hand).name : 'カードが配られると役が表示されます'; }
  function render() { const player = state.players.find(item => item.id === playerId); const turnPlayer = state.players.find(item => item.id === state.currentTurn); $('connectionLabel').textContent = 'Supabase ONLINE'; $('roomLabel').textContent = `TABLE ${roomId.toUpperCase()}`; $('footerRoom').textContent = `ROOM / ${roomId}`; $('roundLabel').textContent = `ROUND ${String(state.round || 1).padStart(2, '0')}`; $('potValue').textContent = state.pot; $('centerPot').textContent = state.pot; $('tableMessage').textContent = state.message; $('centerMessage').innerHTML = state.phase === 'finished' ? `<span class="center-kicker">${state.winner === playerId ? 'YOU WIN' : 'ROUND COMPLETE'}</span><strong>${state.message}</strong>` : '<span class="center-kicker">WELCOME TO THE TABLE</span><strong>待機中</strong>'; $('actionHint').textContent = state.phase === 'waiting' ? 'もう1人の参加者を待っています' : state.phase === 'draw' ? `${turnPlayer?.name || ''}のターン · ${state.exchangeRound} / ${state.settings.turns}` : player?.ready ? '他のプレイヤーを待っています' : 'カードを選んで交換'; $('mainAction').textContent = state.phase === 'finished' ? '次のゲーム' : 'ゲーム開始'; $('mainAction').disabled = !(host() && state.players.length >= 2 && state.phase !== 'draw'); $('foldButton').disabled = state.phase !== 'draw' || player?.ready || state.currentTurn !== playerId; $('settingsButton').disabled = !host() || state.phase === 'draw'; renderPlayers(); renderHand(); }
  function renderRooms(rooms) { const list = document.querySelector('#roomList'); if (!list) return; list.innerHTML = rooms.length ? rooms.map(room => `<article class="room-row"><div><p class="eyebrow">TABLE ${room.id.toUpperCase()}</p><h3>${room.name}</h3><span>${room.playing ? '対戦中' : '参加者を待機中'}</span></div><div class="room-meta"><strong>${room.players} / ${room.maxPlayers}</strong><button class="primary-button join-room" data-room="${room.id}" type="button">参加する <span>↗</span></button></div></article>`).join('') : '<p class="empty-state">公開中の部屋はありません。</p>'; list.querySelectorAll('.join-room').forEach(button => button.addEventListener('click', () => { location.href = `./index.html?roomid=${encodeURIComponent(button.dataset.room)}&name=${encodeURIComponent(name)}`; })); }
  function syncSettingsForm() { Object.entries(state.settings).forEach(([key, value]) => { const input = $(key); if (input) input.value = value; }); }
  function saveSettings(event) { event.preventDefault(); if (!host()) return toast('設定を変更できるのはホストだけです'); const settings = { startingCoins: Math.max(10, Number($('startingCoins').value)), betUnit: Math.max(1, Number($('betUnit').value)), turns: Math.min(5, Math.max(1, Number($('turns').value))), jokerCount: Math.min(5, Math.max(0, Number($('jokerCount').value))), cpuCount: Math.min(5, Math.max(0, Number($('cpuCount').value))) }; handleMessage({ type: 'settings', settings, from: playerId }); $('settingsDialog').close(); toast('設定を保存しました'); }
  function act(payload) { const message = { ...payload, from: playerId }; if (host()) handleMessage(message); else send(payload); }
  $('settingsButton').addEventListener('click', () => { syncSettingsForm(); $('settingsDialog').showModal(); }); $('settingsForm').addEventListener('submit', saveSettings); $('mainAction').addEventListener('click', () => act({ type: 'start' })); $('exchangeButton').addEventListener('click', () => { act({ type: 'draw', indexes: [...selected] }); selected.clear(); }); $('foldButton').addEventListener('click', () => act({ type: 'fold' })); $('clearSelection').addEventListener('click', () => { selected.clear(); renderHand(); }); $('playerHand').addEventListener('click', event => { const card = event.target.closest('.playing-card'); if (!card || state.phase !== 'draw') return; const index = Number(card.dataset.index); selected.has(index) ? selected.delete(index) : selected.add(index); renderHand(); });
  if (roomId) preloadAssets();
  else location.href = './room.html';
})();
